-- Phase 5: LITE + AGENCY pricing tiers
ALTER TYPE "ReportAccessLevel" ADD VALUE IF NOT EXISTS 'LITE';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'LITE';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'AGENCY';
ALTER TYPE "UserPlan" ADD VALUE IF NOT EXISTS 'LITE';
ALTER TYPE "UserPlan" ADD VALUE IF NOT EXISTS 'AGENCY';
