import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Calendar, Clock } from "lucide-react";
import { getPrisma, isDatabaseConfigured } from "@/lib/prisma";
import { trendReportToInsightReport } from "@/lib/content-mappers";
import { siteUrl, pageAlternates } from "@/lib/seo";
import {
  buildInsightArticleJsonLd,
  buildInsightBreadcrumbJsonLd,
} from "@/lib/structured-data";
import { Link } from "@/i18n/navigation";
import { HomeLandingDayNight } from "@/components/home-landing-day-night";
import { AiGenerationBanner } from "@/components/insights/ai-generation-banner";
import { SourcesSection } from "@/components/insights/sources-section";
import { InsightMarkdownBody } from "@/components/insights/markdown-body";

type Params = { params: Promise<{ locale: string; slug: string }> };

export const dynamic = "force-dynamic";

async function loadInsightBySlug(slug: string) {
  if (!isDatabaseConfigured()) return null;
  const db = getPrisma();
  try {
    const row = await db.trendReport.findUnique({ where: { slug } });
    if (!row || row.status !== "published") return null;
    return row;
  } catch (e) {
    console.error(
      "[insights/[slug]] DB lookup failed:",
      e instanceof Error ? e.message : e,
    );
    return null;
  }
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { locale, slug } = await params;
  const row = await loadInsightBySlug(slug);
  if (!row) return { title: "Insight not found | THINKAD" };

  const insight = trendReportToInsightReport(row);
  const description = insight.summaryKo[0]?.slice(0, 220) ?? insight.titleKo;
  const url = `${siteUrl}/${locale}/insights/${slug}`;

  return {
    title: `${insight.titleKo} | THINKAD OOH 인사이트`,
    description,
    alternates: pageAlternates(locale, `/insights/${slug}`),
    openGraph: {
      title: insight.titleKo,
      description,
      url,
      type: "article",
      publishedTime: row.publishedAt?.toISOString(),
      modifiedTime: row.updatedAt.toISOString(),
      siteName: "THINKAD",
      locale: locale === "ko" ? "ko_KR" : "en_US",
      images: row.thumbnailUrl ? [row.thumbnailUrl] : undefined,
    },
    twitter: {
      card: "summary_large_image",
      title: insight.titleKo,
      description,
    },
  };
}

/** 한글 본문 읽기 시간 추정 — 분당 500자. */
function estimateReadMinutes(markdown: string): number {
  const len = markdown.replace(/\s+/g, "").length;
  return Math.max(1, Math.round(len / 500));
}

export default async function InsightDetailPage({ params }: Params) {
  const { locale, slug } = await params;
  const row = await loadInsightBySlug(slug);
  if (!row) notFound();

  const insight = trendReportToInsightReport(row);
  const isAuto = insight.isAutoGenerated === true;
  const sources = insight.sources ?? [];
  const readMinutes = estimateReadMinutes(insight.contentKo ?? "");

  const articleLd = buildInsightArticleJsonLd(
    {
      titleKo: insight.titleKo,
      summaryKo: insight.summaryKo,
      publishedIso: insight.publishedIso,
      slug,
      sources: sources.map((s) => ({ url: s.url, title: s.title })),
    },
    locale,
  );
  const breadcrumbLd = buildInsightBreadcrumbJsonLd(
    { titleKo: insight.titleKo, slug },
    locale,
  );

  return (
    <HomeLandingDayNight>
      <div className="tkad-landing-neon tkad-planner-neon">
        <main className="mx-auto max-w-4xl px-4 py-12 sm:px-6">
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(articleLd) }}
          />
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }}
          />

          <nav className="mb-6 font-mono text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
            <Link
              href="/insights"
              className="transition-colors hover:text-primary"
            >
              ← OOH 인사이트
            </Link>
          </nav>

          <header className="space-y-4">
            <p className="font-mono text-[11px] uppercase tracking-[0.22em] text-primary">
              {`// INSIGHT / ${slug.slice(0, 8).toUpperCase()}`}
            </p>
            <div className="flex flex-wrap items-center gap-1">
              <span className="border-2 border-border bg-hero-void px-2 py-0.5 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-hero-fg">
                [ {insight.period === "monthly" ? "월간" : "분기"} ]
              </span>
              <span className="border-2 border-border bg-card px-2 py-0.5 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-foreground">
                {locale === "ko" ? insight.labelKo : insight.labelEn}
              </span>
              {isAuto ? (
                <span className="border-2 border-primary bg-primary px-2 py-0.5 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-primary-foreground">
                  AI 분석
                </span>
              ) : null}
            </div>

            <h1 className="text-3xl font-bold leading-tight tracking-tight text-foreground sm:text-5xl">
              {locale === "ko" ? insight.titleKo : insight.titleEn}
            </h1>

            <div className="flex flex-wrap items-center gap-x-4 gap-y-1 font-mono text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
              <span className="flex items-center gap-1">
                <Calendar className="h-3.5 w-3.5" aria-hidden />
                {insight.publishedIso}
              </span>
              <span className="flex items-center gap-1">
                <Clock className="h-3.5 w-3.5" aria-hidden />약 {readMinutes}분
                읽기
              </span>
            </div>
          </header>

          {isAuto ? (
            <div className="mt-6">
              <AiGenerationBanner />
            </div>
          ) : null}

          {insight.summaryKo.length > 0 ? (
            <section
              aria-label="요약"
              className="mt-8 border-2 border-primary bg-card p-5"
            >
              <p className="font-mono text-[10px] font-bold uppercase tracking-[0.22em] text-primary">
                [ TL;DR ]
              </p>
              <ul className="mt-3 space-y-2 text-sm leading-relaxed text-foreground">
                {insight.summaryKo.slice(0, 5).map((line, i) => (
                  <li key={i} className="flex gap-2">
                    <span aria-hidden className="mt-0.5 text-primary">
                      ▸
                    </span>
                    <span>{line}</span>
                  </li>
                ))}
              </ul>
            </section>
          ) : null}

          {insight.contentKo ? (
            <article className="mt-8">
              <InsightMarkdownBody markdown={insight.contentKo} />
            </article>
          ) : null}

          <SourcesSection sources={sources} />

          <p className="mt-8 border-2 border-border bg-muted p-4 font-mono text-[11px] leading-relaxed tracking-tight text-muted-foreground">
            {`// `}본 리포트는 AI 가 자동 생성한 분석 자료로, THINKAD 자체
            검증을 거쳤으나 의사결정에 활용하실 때는 추가 검증을 권장드립니다.
          </p>
        </main>
      </div>
    </HomeLandingDayNight>
  );
}
