export interface MediaItem {
  id: number;
  name: string;
  nameEn: string;
  location: string;
  locationEn: string;
  region: string;
  type: string;
  price: number;
  lat: number;
  lng: number;
  dailyFootTraffic: number;
  monthlyFootTraffic?: number;
  size?: string;
  resolution?: string;
  brightness?: string;
  targetAge?: string;
  features?: string;
  featuresEn?: string;
  dailyExposure?: string;
  sampleImages: string[];
}

export const mediaData: MediaItem[] = [
  {
    id: 1,
    name: "코엑스 K-POP 스퀘어",
    nameEn: "COEX K-POP Square LED",
    location: "서울 강남구 영동대로 513 코엑스",
    locationEn: "COEX, 513 Yeongdong-daero, Gangnam-gu, Seoul",
    region: "seoul",
    type: "digital",
    price: 5000,
    lat: 37.5112,
    lng: 127.0595,
    dailyFootTraffic: 450000,
    monthlyFootTraffic: 5000000,
    size: "80.9m × 20.1m (1,620㎡)",
    resolution: "7,840 × 1,952px",
    brightness: "9,000nit",
    targetAge: "20-40대, K-POP 팬, 관광객",
    features: "국내 최대 커브드 LED, 애너모픽 3D 가능, 농구장 4배 크기",
    featuresEn: "Korea's largest curved LED, anamorphic 3D capable, 4x basketball court size",
    dailyExposure: "450,000",
    sampleImages: [],
  },
  {
    id: 2,
    name: "강남대로 미디어폴 G-LIGHT",
    nameEn: "Gangnam-daero Media Pole G-LIGHT",
    location: "강남역-신논현역 760m 구간",
    locationEn: "760m section between Gangnam Stn – Sinnonhyeon Stn",
    region: "seoul",
    type: "digital",
    price: 4000,
    lat: 37.4979,
    lng: 127.0276,
    dailyFootTraffic: 300000,
    size: "1.5m × 5.34m × 18기",
    targetAge: "20-30대, 강남 직장인/소비자",
    features: "18기 동시 송출, 성별 인식 맞춤 광고",
    featuresEn: "18 poles simultaneous broadcast, gender-recognition targeted ads",
    dailyExposure: "300,000+",
    sampleImages: [],
  },
  {
    id: 3,
    name: "신논현역 DSG빌딩 전광판",
    nameEn: "Sinnonhyeon DSG Building LED",
    location: "강남대로 신논현역 사거리",
    locationEn: "Sinnonhyeon Stn intersection, Gangnam-daero",
    region: "seoul",
    type: "digital",
    price: 2800,
    lat: 37.5044,
    lng: 127.0254,
    dailyFootTraffic: 250000,
    targetAge: "강남 상권 소비자",
    features: "강남대로 초입 랜드마크, 높은 시인성",
    featuresEn: "Gangnam-daero entrance landmark, high visibility",
    dailyExposure: "250,000",
    sampleImages: [],
  },
  {
    id: 4,
    name: "청담동 학동사거리 SS타워 전광판",
    nameEn: "Cheongdam SS Tower LED",
    location: "서울 강남구 학동사거리",
    locationEn: "Hakdong intersection, Gangnam-gu, Seoul",
    region: "seoul",
    type: "digital",
    price: 3200,
    lat: 37.5169,
    lng: 127.0397,
    dailyFootTraffic: 200000,
    targetAge: "청담동 프리미엄 소비자",
    features: "국내 최장 가시거리, 청담 프리미엄 상권",
    featuresEn: "Longest viewing distance in Korea, Cheongdam premium district",
    dailyExposure: "200,000",
    sampleImages: [],
  },
  {
    id: 5,
    name: "성수동 반도 외벽광고",
    nameEn: "Seongsu Bando Exterior Ad",
    location: "서울 성동구 성수동2가",
    locationEn: "Seongsu-dong 2-ga, Seongdong-gu, Seoul",
    region: "seoul",
    type: "billboard",
    price: 2000,
    lat: 37.5445,
    lng: 127.056,
    dailyFootTraffic: 180000,
    targetAge: "MZ세대, 성수 트렌드세터",
    features: "중앙감속기·피치스도원 인근, 성수 핫플레이스",
    featuresEn: "Near Junggang Gamsoek-gi & Peaches Do-won, Seongsu hotspot",
    dailyExposure: "180,000",
    sampleImages: [],
  },
  {
    id: 6,
    name: "지하철 2호선 성수역 디지털광고",
    nameEn: "Seongsu Station Line 2 Digital Ad",
    location: "서울 성동구 성수역",
    locationEn: "Seongsu Station, Seoul",
    region: "seoul",
    type: "subway",
    price: 1500,
    lat: 37.5445,
    lng: 127.0559,
    dailyFootTraffic: 100000,
    targetAge: "2호선 이용객, MZ세대",
    features: "2호선 유동인구 상위역, 디지털 스크린",
    featuresEn: "Top-traffic Line 2 station, digital screens",
    dailyExposure: "100,000+",
    sampleImages: [],
  },
  {
    id: 7,
    name: "뉴욕 타임스퀘어 전광판",
    nameEn: "New York Times Square LED",
    location: "뉴욕 맨해튼 타임스퀘어",
    locationEn: "Times Square, Manhattan, New York",
    region: "national",
    type: "digital",
    price: 8000,
    lat: 40.758,
    lng: -73.9855,
    dailyFootTraffic: 330000,
    targetAge: "글로벌 소비자, 관광객",
    features: "세계적 랜드마크, 24시간 노출",
    featuresEn: "World-class landmark, 24h exposure",
    dailyExposure: "330,000",
    sampleImages: [],
  },
  {
    id: 8,
    name: "두바이 부르즈 할리파 LED",
    nameEn: "Dubai Burj Khalifa LED",
    location: "두바이 부르즈 할리파",
    locationEn: "Burj Khalifa, Dubai, UAE",
    region: "national",
    type: "digital",
    price: 9500,
    lat: 25.1972,
    lng: 55.2744,
    dailyFootTraffic: 250000,
    size: "828m 건물 전체 LED",
    targetAge: "글로벌 프리미엄 소비자",
    features: "세계 최고층 건물 광고, 828m 건물 전체 LED",
    featuresEn: "World's tallest building ad, full 828m building LED",
    dailyExposure: "250,000",
    sampleImages: [],
  },
  {
    id: 9,
    name: "일본 애드트럭",
    nameEn: "Japan Ad Truck",
    location: "도쿄, 오사카 등 일본 전역",
    locationEn: "Tokyo, Osaka & major cities across Japan",
    region: "national",
    type: "bus",
    price: 1800,
    lat: 35.6762,
    lng: 139.6503,
    dailyFootTraffic: 200000,
    targetAge: "일본 도심 소비자",
    features: "이동형 광고매체, 일본 주요 도시 운행",
    featuresEn: "Mobile ad vehicle, operates in major Japanese cities",
    dailyExposure: "200,000",
    sampleImages: [],
  },
  {
    id: 10,
    name: "코엑스 파르나스 미디어타워",
    nameEn: "COEX Parnas Media Tower",
    location: "삼성역 코엑스",
    locationEn: "COEX, Samsung Station, Seoul",
    region: "seoul",
    type: "digital",
    price: 3500,
    lat: 37.5085,
    lng: 127.0635,
    dailyFootTraffic: 300000,
    targetAge: "비즈니스·MICE 참가자, 강남 소비자",
    features: "고급스러운 조형미, 삼성역 랜드마크",
    featuresEn: "Elegant sculptural design, Samsung Station landmark",
    dailyExposure: "300,000",
    sampleImages: [],
  },
];

export const typeLabels: Record<string, { ko: string; en: string }> = {
  billboard: { ko: "빌보드", en: "Billboard" },
  digital: { ko: "디지털", en: "Digital" },
  subway: { ko: "지하철", en: "Subway" },
  bus: { ko: "버스/트럭", en: "Bus/Truck" },
};
