import { notFound } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { CheckCircle2 } from "lucide-react";
import { BtnBlock } from "@/components/brutalist";
import { PaymentHapticTrigger } from "@/components/mobile/payment-haptic-trigger";
import { getPrisma } from "@/lib/prisma";
import { resolveLocaleParam } from "@/lib/resolve-locale"; type Props = { params: Promise<{ locale: string; id: string }> }; const PAID_STATUSES = new Set(["paid", "confirmed"]); export default async function BookingConfirmationPage({ params }: Props) { const locale = await resolveLocaleParam(params); setRequestLocale(locale); const { id } = await params; const db = getPrisma(); const booking = await db.booking.findUnique({ where: { id }, include: { media: { select: { id: true, name: true, location: true } } }, }); if (!booking) notFound(); const t = await getTranslations("instantBooking.confirm"); const isKo = locale === "ko"; const paid = PAID_STATUSES.has(booking.status); const start = booking.startDate.toISOString().slice(0, 10); const end = booking.endDate.toISOString().slice(0, 10); return ( <main className="mx-auto max-w-lg px-4 py-12 sm:px-6"> <PaymentHapticTrigger active={paid} /> <div className="rounded-[24px] border border-border bg-card p-8 shadow-sm"> {paid ? ( <CheckCircle2 className="h-12 w-12 text-primary" aria-hidden /> ) : null} <h1 className="mt-4 text-2xl font-black tracking-tight"> {paid ? t("titlePaid") : t("titlePending")} </h1> <p className="mt-2 text-sm text-muted-foreground"> {paid ? t("descPaid") : t("descPending")} </p> <dl className="mt-8 space-y-3 text-sm"> <div> <dt className="font-display text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground"> {t("media")} </dt> <dd className="font-semibold">{booking.media.name}</dd> </div> <div> <dt className="font-display text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground"> {t("period")} </dt> <dd> {start} ~ {end} </dd> </div> <div> <dt className="font-display text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground"> {t("amount")} </dt> <dd className="text-lg font-black"> {booking.amount.toLocaleString(isKo ? "ko-KR" : "en-US")}원 </dd> </div> <div> <dt className="font-display text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground"> {t("status")} </dt> <dd>{t(`status_${booking.status}` as "status_paid")}</dd> </div> {booking.executionConfirmedAt ? ( <div> <dt className="font-display text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground"> {t("executionConfirmed")} </dt> <dd> {booking.executionConfirmedAt.toISOString().slice(0, 10)} </dd> </div> ) : null} </dl> <div className="mt-8 flex flex-col gap-2"> {!paid && booking.status === "payment_pending" ? ( <BtnBlock href={`/bookings/${id}/pay`} variant="accent" size="lg"> {t("continuePay")} </BtnBlock> ) : null} <BtnBlock href={`/media/${booking.media.id}`} variant="secondary" size="md" > {t("backMedia")} </BtnBlock> </div> </div> <p className="mt-6 text-center text-xs text-muted-foreground"> {t("emailHint", { email: booking.contactEmail })} </p> </main> );
}
